# Generated by Django 3.2.7 on 2021-09-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='predio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula_catastral', models.CharField(max_length=19)),
                ('direccion', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('R', 'rural'), ('U', 'urbanos')], max_length=1)),
            ],
        ),
    ]
