# Generated by Django 3.2.7 on 2021-09-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predio',
            name='identificacion',
            field=models.CharField(default='00000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='predio',
            name='tipo',
            field=models.CharField(choices=[('R', 'rural'), ('U', 'urbanos')], default='urbanos', max_length=1),
        ),
    ]
