# Generated by Django 3.2.7 on 2021-09-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_auto_20210919_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predio',
            name='tipo',
            field=models.CharField(choices=[('U', 'urbanos'), ('R', 'rural')], default='rural', max_length=1),
        ),
    ]
